### PR TITLE
fix: handle deployment selection inconsistencies

### LINKED ISSUE #49: Contract script is missing. Rebuild the contract
image

### PR DESCRIPTION
**Pull request by rahulyadav-57**
Resolves #49

### CODE REVIEW

File: src/components/workspace/BuildProject/BuildProject.tsx [hunk 1]
```diff
@@ -102,23 +102,29 @@ const BuildProject: FC<Props> = ({ projectId, contract, updateContract }) => {
...
     return projectFiles
-      .filter((f) => {
-        const _fileExtension = getFileExtension(f.name || '');
-        return (
-          f.path.startsWith(`${activeProject?.path}/dist`) &&
-          ['abi'].includes(_fileExtension as string)
+      .filter((file) => {
+        const fileExtension = getFileExtension(file.name || '');
+        const isAbiFile =
+          file.path.startsWith(`${activeProject?.path}/dist`) &&
```
Comment (verytactical) [inline src/components/workspace/BuildProject/BuildProject.tsx:108]: Please encapsulate all the logic related to filenames into a separate file.

If there is another place in the code that would need to check if the file is an ABI-file, it would be found there.

The underlying problem is that file paths are usually untyped, and it's unsafe to work with them with String methods. While working with paths as if they were Strings is not avoidable (that's the OS interface to work with files after all), it's possible to at least give proper attention to changes of unsafe code, if it's encapsulated in a separate file.

File: src/components/workspace/BuildProject/BuildProject.tsx [hunk 2]
```diff
@@ -102,23 +102,29 @@ const BuildProject: FC<Props> = ({ projectId, contract, updateContract }) => {
...
-            .replace('.abi', '')
-            .replace('tact_', '')
-            .replace('func_', ''),
-          path: f.path,
-        };
-      });
+      .map((file) => ({
+        id: file.id,
+        name: file.name
+          .replace('.abi', '')
```
Comment (verytactical) [inline src/components/workspace/BuildProject/BuildProject.tsx:123]: These strings are repeated several times over the code base, and in case there'll be a change to them, there'll be no way to ensure modification is consistent.

It'd be better to assign this `replace` action a name and encapsulate all the related strings in a single file.

File: src/components/workspace/BuildProject/BuildProject.tsx [hunk 3]
```diff
@@ -638,9 +644,29 @@ const BuildProject: FC<Props> = ({ projectId, contract, updateContract }) => {
...
     }
-    if (activeProject?.selectedContract) {
-      setSelectedContract(activeProject.selectedContract);
-      deployForm.setFieldsValue({ contract: activeProject.selectedContract });
+    const selectedABIPath = activeProject?.selectedContract;
+
+    if (selectedABIPath) {
+      const correspondingScriptPath = selectedABIPath.replace('.abi', '.ts');
+
+      let _selectedContract: string | undefined = selectedABIPath;
```
Comment (verytactical) [inline src/components/workspace/BuildProject/BuildProject.tsx:652]: This variable is used. `_` convention is for variables that are unused, or for private class fields.

File: src/components/workspace/BuildProject/BuildProject.tsx [hunk 4]
```diff
@@ -638,9 +644,29 @@ const BuildProject: FC<Props> = ({ projectId, contract, updateContract }) => {
     if (activeProject?.network) {
       setEnvironment(activeProject.network);
     }
-    if (activeProject?.selectedContract) {
-      setSelectedContract(activeProject.selectedContract);
-      deployForm.setFieldsValue({ contract: activeProject.selectedContract });
+    const selectedABIPath = activeProject?.selectedContract;
+
+    if (selectedABIPath) {
+      const correspondingScriptPath = selectedABIPath.replace('.abi', '.ts');
```
Comment (verytactical) [inline src/components/workspace/BuildProject/BuildProject.tsx:650]: - These strings are repeated in other parts of code.
- The replace goes over the whole string, and `.abi` can be any part of it. For example, `.abi`, `.abi.foo.cpp` or `h.abibi.txt`.

File: src/components/workspace/BuildProject/BuildProject.tsx [hunk 5]
```diff
@@ -638,9 +644,29 @@ const BuildProject: FC<Props> = ({ projectId, contract, updateContract }) => {
     if (activeProject?.network) {
       setEnvironment(activeProject.network);
     }
-    if (activeProject?.selectedContract) {
-      setSelectedContract(activeProject.selectedContract);
-      deployForm.setFieldsValue({ contract: activeProject.selectedContract });
+    const selectedABIPath = activeProject?.selectedContract;
```
Comment (verytactical) [inline src/components/workspace/BuildProject/BuildProject.tsx:647]: Abbreviations in camel case are handled as regular words.

[Here's a review](https://stackoverflow.com/questions/15526107/acronyms-in-camelcase) of the reasoning behind it.

The most important part there is that automated tools can only work if rules do not depend on semantics. For example, if there would be a file that exports `selectedABIPath`, its name by Node.js file naming standards would be `selected-a-b-i-path`, and linter would enforce that.

File: src/components/workspace/BuildProject/BuildProject.tsx (hunk 3 above)
Comment (verytactical) [inline src/components/workspace/BuildProject/BuildProject.tsx:652]: This variable doesn't have to be mutable. By abstracting the logic into `getSelectedContract()` it could be just a `return`.

**Comment by verytactical** [comment]
This is open for 3 weeks without progress. Should we close it?

**Review by anton-trunov — CHANGES_REQUESTED** [review]
@rahulyadav-57 please resolve the comments

**Comment by rahulyadav-57** [comment]
I was working on Misti support, so it was delayed. I'll resolve it soon.

File: src/components/workspace/BuildProject/BuildProject.tsx (hunk 5 above)
Comment (rahulyadav-57) [reply src/components/workspace/BuildProject/BuildProject.tsx:648]: Currently, we use this uppercase format for ABI throughout the project, so for consistency, I would prefer to keep it as is. However, we'll consider revisiting naming conventions during a broader codebase refactor in the future. I appreciate your attention to detail!

File: src/components/workspace/BuildProject/BuildProject.tsx [hunk 6]
```diff
@@ -406,9 +412,12 @@ const BuildProject: FC<Props> = ({ projectId, contract, updateContract }) => {
...
       const finalJsoutput = fromJSModule((jsOutout as OutputChunk[])[0].code);
 
-      const contractName = extractContractName(selectedContract);
+      const contractName = extractContractName(
+        selectedContract,
+        activeProject.path,
+      );
 
-      if (activeProject?.language == 'tact') {
+      if (activeProject.language == 'tact') {
```
Comment (verytactical) [inline src/components/workspace/BuildProject/BuildProject.tsx:420]: nit: `===`

**Review by verytactical — APPROVED** [review]
.
